<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <title>Laporan Cuti - {{ $period }}</title>
    <style>
        /* Simplified styles compatible with Dompdf */
        body {
            font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
            color: #111;
            font-size: 12px;
        }

        .header-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 6px;
        }

        .logo {
            width: 72px;
            height: 72px;
            background: #f3f4f6;
            display: inline-block;
            text-align: center;
            vertical-align: middle;
            border-radius: 6px;
            font-weight: bold;
            line-height: 72px;
        }

        .title {
            text-align: center;
            font-size: 14px;
        }

        .title h1 {
            margin: 0;
            font-size: 16px;
        }

        .meta {
            text-align: right;
            font-size: 11px;
            color: #555;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 8px;
            table-layout: fixed;
            /* ensure column widths are respected */
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 6px 8px;
            font-size: 11px;
            vertical-align: top;
            word-wrap: break-word;
            overflow-wrap: break-word;
            white-space: normal;
        }

        th {
            background: #f8fafc;
            text-align: left;
        }

        .footer {
            margin-top: 12px;
            font-size: 11px;
            color: #666;
        }

        @page {
            margin: 15mm 12mm;
        }
    </style>
</head>

<body>
    <table class="header-table">
        <tr>
            <td style="width:90px">
                @if (!empty($kop_logo))
                    <div style="text-align:center">
                        <img src="{{ $kop_logo }}" alt="Kop"
                            style="max-width:90px; max-height:90px; border-radius:4px;" />
                    </div>
                @else
                    <div class="logo">LOGO</div>
                @endif
            </td>
            <td style="text-align:center">
                <div class="title">
                    <h1>Laporan Cuti</h1>
                    <div style="font-size:12px;color:#444">Periode: {{ $period }}</div>
                </div>
            </td>
            <td style="width:160px;vertical-align:top;text-align:right">
                <div class="meta">Dicetak: {{ now()->format('d M Y H:i') }}</div>
                @if ($query)
                    <div class="meta">Filter: "{{ $query }}"</div>
                @endif
            </td>
        </tr>
    </table>

    <table>
        <colgroup>
            <col style="width:40px">
            <col style="width:140px">
            <col style="width:120px">
            <col style="width:140px">
            <col style="width:160px">
            <col style="width:70px">
            <col style="width:140px">
            <col style="width:120px">
            <col>
        </colgroup>
        <thead>
            <tr>
                <th style="width:40px">No</th>
                <th>Nama</th>
                <th>Divisi</th>
                <th>Jenis</th>
                <th style="width:150px">Tanggal</th>
                <th style="width:80px">Durasi</th>
                <th>Pelimpahan</th>
                <th style="width:120px">Telp</th>
                <th>Keterangan</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $i => $r)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $r['nama'] }}</td>
                    <td>{{ $r['divisi'] }}</td>
                    <td>{{ $r['jenis'] }}</td>
                    <td>{{ $r['tanggal_mulai'] }}{{ $r['tanggal_selesai'] ? ' — ' . $r['tanggal_selesai'] : '' }}</td>
                    <td style="text-align:center">{{ $r['durasi'] }}</td>
                    <td>{{ $r['pelimpahan'] }}</td>
                    <td>{{ $r['telp'] }}</td>
                    <td>{{ $r['alasan'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align:center;color:#666">Tidak ada data untuk periode ini.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <div>Generated by {{ config('app.name') }}</div>
        <div>Total records: {{ count($rows) }}</div>
    </div>
</body>

</html>
